### ISSUE TITLE
网络学堂爬虫  跨学期同名课程重名问题

### ISSUE THREAD

**Issue by Nangos** [Yiping-Steven/Memory_fetcher#1]
```
DEBUG:root:欢迎大家继续学习《电子技术实验》!
DEBUG:root:电子技术实验(0)
Traceback (most recent call last):
  File "crawler_learn.py", line 16, in <module>
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'learn/电子技术实验(0)'
```
疑似因电子技术实验(0)课程跨两个学期而导致的文件名重名造成程序异常退出。

**Comment by Yiping-Steven** [comment]
6月1日的更新里改进了路径检查特性，现在应该已经没这问题了。
